backend:
  name: git-gateway
  branch: main  # Change si nécessaire

media_folder: "public/images/uploads"  # Où sont stockées les images
public_folder: "/images/uploads"

collections:
  # ✅ Page d'accueil
  - name: "homepage"
    label: "Page d'accueil"
    files:
      - file: "src/content/homepage.md"
        label: "Page d'accueil"
        name: "homepage"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Image avant", name: "hero_image_before", widget: "image" }
          - { label: "Image après", name: "hero_image_after", widget: "image" }
          - { label: "Description", name: "description", widget: "text" }
          - label: "Réalisations mises en avant"
            name: "featured_realisations"
            widget: "object" 
            fields:
              - { label: "Titre", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - label: "Sélection des réalisations"
                name: "items"
                widget: "relation"
                collection: "realisations"
                multiple: true
                search_fields: ["title"]
                value_field: "title"
                display_fields: ["title"]
                max: 3  #
          - label: "Engagements"
            name: "engagements"
            widget: "object"  
            fields:
              - { label: "Titre", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - label: "Liste des engagements"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Titre", name: "block_title", widget: "string" }
                  - { label: "Description", name: "block_description", widget: "text" }
          - label: "Expertises"
            name: "expertises"
            widget: "object"
            fields:
              - { label: "Titre", name: "title", widget: "string" }
              - label: "Liste des expertises"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Titre", name: "block_title", widget: "string" }
                  - { label: "Description", name: "block_description", widget: "text" }
          - label: "Équipe"
            name: "equipe"
            widget: "object"
            fields:
              - { label: "Titre", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }
          - label: "Certification et assurances"
            name: "certifications"
            widget: "object"
            fields:
              - { label: "Titre", name: "title", widget: "string" }
              - label: "Liste des certifications"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Titre", name: "block_title", widget: "string" }
                  - { label: "Description", name: "block_description", widget: "text" }
                  - { label: "Image", name: "block_image", widget: "image" }

  # ✅ Liste des réalisations
  - name: "realisations"
    label: "Réalisations"
    folder: "src/content/realisations"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Image principale", name: "hero_image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - label: "Caractéristiques"
        name: "caracteristiques"
        widget: "list"
        fields:
          - { label: "Nom", name: "block_title", widget: "string" }
          - { label: "Valeur", name: "block_value", widget: "string" }
        default:
        - block_title: "Maitre d’ouvrage"
          block_value: "Novalex"
        - block_title: "Adresse"
          block_value: ""
        - block_title: "Date"
          block_value: "02/04/2025"
        - block_title: "Spécificités techniques"
          block_value: ""
      - label: "Galerie d'images"
        name: "gallery"
        widget: "list"
        fields:
          - { label: "Titre de la section", name: "block_title", widget: "string", required: false }
          - { label: "Images", name: "images", widget: "list", fields: [{ label: "Image", name: "image", widget: "image" }] }

  # ✅ Page listant toutes les réalisations
  - name: "realisation_list"
    label: "Page des réalisations"
    files:
      - file: "src/content/realisation.md"
        label: "Page des réalisations"
        name: "realisation_list"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Texte d'introduction", name: "description", widget: "text" }
          - { label: "Image principale", name: "hero_image", widget: "image" }


  # ✅ Configuration générale du site
  - name: "config"
    label: "Configuration du site"
    files:
      - file: "src/content/config.md"
        label: "Configuration du site"
        name: "config"
        fields:
          - { label: "Adresse", name: "address", widget: "string" }
          - { label: "Google maps", name: "maps_link", widget: "string" }
          - { label: "Logo", name: "logo", widget: "image" }
          - { label: "Téléphone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
